name: 'Load to S3'
description: 'Syncs a repo folder with a s3 folder'

inputs:
   aws-access-key-id:
     required: true
     description: "The aws-access-key-id used to authenticate with AWS"
   aws-secret-access-key:
     required: true
     description: "The aws-secret-access-key used to authenticate with AWS"
   aws-region: 
      required: true
      description: "The aws-region for s3"
   source-folder:
     required: true
     description: "source folder"
   target-folder:
     required: true
     description: "path to target s3 folder"
-

runs:
  using: "composite"
  steps:
  
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
        # Actions cannot access secrets so pass them in as inputs
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

  - name: copy to s3
    run: |
      aws s3 sync ${{ inputs.source-folder }}/ s3://${{ inputs.target-folder }}/ --exclude '.git*'
