def to_upper(input_str):

    return """  
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO
        HOLA MUNDO HOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDOHOLA MUNDO        
    """


def to_lower(input_str):

    return input_str.lower()
