name: Build and load to S3

on:
  release:
    types: [published]

jobs:
  build-repo:
    runs-on: ubuntu-latest
    steps:
      #checking out the repo in the worker, it uses the branch who kicked off the release
    - uses: actions/checkout@v3
      
      # temporary directory to create the comprressed version of repo.
      # this is necessary to avoid recursively compressing the repo onto itself.

    - name: Make artifact directory
      run: mkdir -p ./artifacts

      # Build compressed version of repo and deleting the mporary folder  --exclude ".git*"
    - name:  Build compressed repo
      run: |
        tar -zcvf ./artifacts/source.tar.gz .
        mv ./artifacts/source.tar.gz .
        rm -r ./artifacts
    
    - name: Upload repo and compressed repo version
      uses: actions/upload-artifact@v3
      with:
        name: my-repository
        path: ${{ github.workspace }}
  
  dev-deploy:

    name: Dev Deploy
    if:  startsWith(github.event.release.tag_name, 'experiment')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: DEV
    needs: build-repo
    steps:
      
      - name: Download build 
        uses: actions/download-artifact@v3
        with: 
          name: my-repository
      
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      
      - name: List files in the workdir
        run: |
          ls -la .

      - name: Deploy to AWS s3
        uses: ./.github/actions/deploy-to-s3/
        with: 
          aws-role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.aws-region }}
          source-folder: ${{ github.workspace }}
          target-folder: ${{ vars.BUCKET_NAME }}/${{ github.event.repository.name }}
  
  prod-deploy:
    
    name: Prod Deploy
    if:  startsWith(github.event.release.tag_name, 'release')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: PROD
    needs: dev-deploy
    steps:
 
      - name: Download build 
        uses: actions/download-artifact@v3
        with: 
          name: my-repository

      - name: Deploy to AWS s3
        uses: ./.github/actions/deploy-to-s3/
        with: 
          aws-role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.aws-region }}
          source-folder: ${{ github.workspace }}
          target-folder: ${{ vars.BUCKET_NAME }}/${{ github.event.repository.name }}