name: Build and load to S3 with multibranch approach

on:
  release:
    types: [published]

jobs:

  dev-deploy:

    name: Dev Deploy
    if:  startsWith(github.event.release.tag_name, 'experiment')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: DEV
    steps:
    
    - uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-session-name: github-actions-role
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Make artifact directory
      run: mkdir -p ./artifacts

    - name:  Copy build to S3
      run: |
        tar --exclude ".git*" -zcvf ./artifacts/source.tar.gz .
        mv ./artifacts/source.tar.gz .
        aws s3 sync  ${GITHUB_WORKSPACE}/ s3://${{env.BUCKET_NAME}}/${{ github.actor }}/${{ github.event.repository.name }}/ --exclude '.git*' --exclude './artifacts/*'
  
  prod-deploy:
    name: Prod Deploy
    if:  startsWith(github.event.release.tag_name, 'release')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: PROD
    steps:
    
    - uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-session-name: github-actions-role
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Make artifact directory
      run: mkdir -p ./artifacts

    - name:  Copy build to S3
      run: |
        tar --exclude ".git*" -zcvf ./artifacts/source.tar.gz .
        mv ./artifacts/source.tar.gz .
        aws s3 sync  ${GITHUB_WORKSPACE}/ s3://${{env.BUCKET_NAME}}/${{ github.event.repository.name }}/ --exclude '.git*' --exclude './artifacts/*'