name: Build and load to S3

on:
  workflow_dispatch: {}

env:
  BUCKET_NAME : "github-actions-devbucket"
  AWS_REGION : "us-east-1"

jobs:
  build:
    name: Build zip file
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::002680663754:role/github-actions-role
          role-session-name: github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Make artifact directory
        run: mkdir -p ./artifacts

      # Copy build directory to S3
      - name:  Copy build to S3
        run: |
          zip -r ./artifacts/project.zip . -x .git/**\*  
          aws s3 sync  ${GITHUB_WORKSPACE}/artifacts s3://${{ env.BUCKET_NAME }}/${{ steps.extract_branch.outputs.branch }}/latest