name: Lint Python Code

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint code
        run: |
          flake8 . > lint.txt || true
          exit_status=$?
          echo "::set-output name=exit_status::$exit_status"

      - name: Comment on pull request
        uses: actions/github-script@v5
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const exitStatus = parseInt('${{ steps.lint.outputs.exit_status }}');
            if (exitStatus !== 0) {
              const lintOutput = fs.readFileSync('lint.txt', 'utf8');
              const context = github.context;
              const { owner, repo, number } = context.issue;
              github.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: `The code did not pass flake8 linting. Please fix the issues before merging.\n\n\`\`\`\n${lintOutput}\n\`\`\`\n`,
              });
            }