name: Matrix with multiple variables

on: workflow_dispatch 

jobs:

  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parse_matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse matrix file
        id: parse_matrix
        run: |
          matrix=()
          while IFS= read -r line; do
            matrix+=("$line")
          done < matrix.txt
          matrix_output=""
          for m in "${matrix[@]}"; do
            matrix_output+=$(printf ",%s" "$m")
          done
          echo "::set-output name=matrix::${matrix_output:1}"
  
  build:
    needs: get_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ needs.get_matrix.outputs.matrix.os }}
        language: ${{ needs.get_matrix.outputs.matrix.language }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build on ${{ matrix.os }} with ${{ matrix.language }} version ${{ matrix.version }}
        run: echo "Building on ${{ matrix.os }} with ${{ matrix.language }} version ${{ matrix.version }}"

      # additional steps...