name: Build and load to S3 with multibranch approach

on:
  workflow_call:
    inputs: 
      aws_region: 
        description: 's3 aws region'
        required: true
        type: string
      bucket_name:
        description: 'Bucket name [and path] where release is being deployed.'
        required: true
        type: string
      dev_trigger_prefix:
        description: 'This is the prefix tag to identify a release as a Dev release.'
        required: false
        type: string
        default: 'experiment'
      prod_trigger_prefix:
        description: 'This is the prefix tag to identify a release as a Prod release.'
        required: false
        type: string
        default: 'release'
    secrets:
      aws_role_to_assume:
        required: true
      

jobs:
  build-repo:
    
    #runner
    runs-on: ubuntu-latest
    steps:

    #checking out the repo in the worker, it uses the branch who kicked off the release
    - uses: actions/checkout@v3
      
    # temporary directory to create the comprressed version of repo.
    # this is necessary to avoid recursively compressing the repo onto itself.
    - name: Make artifact directory
      run: mkdir -p ./artifacts

    # Build compressed version of repo and deleting the mporary folder  --exclude ".git*"
    - name:  Build compressed repo
      run: |
        tar -zcvf ./artifacts/source.tar.gz .
        mv ./artifacts/source.tar.gz .
        rm -r ./artifacts
    
    # Upload artifact to it is ready for use either by dev or prod workflows.
    - name: Upload repo and compressed repo version
      uses: actions/upload-artifact@v3
      with:
        name: my-repository
        path: ${{ github.workspace }}
  
  dev-deploy:

    name: Dev Deploy
    if:  startsWith(github.event.release.tag_name, ${{ inputs.dev_trigger_prefix }})
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: DEV
    needs: build-repo
    steps:
      - name: Download reusable repo
        uses: actions/checkout@v3
          repository: hcastrofactored/github-actions-testing

      - name: Download build 
        uses: actions/download-artifact@v3
        with: 
          name: my-repository
          path: my-repository

      - name: Deploy to AWS s3
        uses: ./.github/actions/deploy-to-s3/
        with: 
          aws-role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region:  ${{ inputs.aws_region }}
          source-folder: ${{ github.workspace }}/my-repository/
          target-folder: ${{ inputs.bucket_name }}/${{ github.actor }}/${{ github.event.repository.name }}
  
  prod-deploy:
    
    name: Prod Deploy
    if:  startsWith(github.event.release.tag_name, ${{ inputs.prod_trigger_prefix }})
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: PROD
    needs: build-repo
    steps:

       - name: Download reusable repo
         uses: actions/checkout@v3
          repository: hcastrofactored/github-actions-testing
          
      - name: Download build 
        uses: actions/download-artifact@v3
        with: 
          name: my-repository
          path: my-repository

      - name: Deploy to AWS s3
        uses: ./.github/actions/deploy-to-s3/
        with: 
          aws-role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
          source-folder: ${{ github.workspace }}/my-repository/
          target-folder: ${{ inputs.bucket_name }}/${{ github.event.repository.name }}