name: Project test 

on: 
  pull_request:
    branches:
      - main 

jobs: 
  build: 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      id-token: write
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.7'
            cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flake8
        id: flake8
        run: |
          flake8 --max-line-length 120 .

      - name: Comment on pull request
        uses: actions/github-script@v4
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `<details><summary>Flake8 Output</summary>

            \`\`\`
            ${JSON.stringify({annotations: context.payload.pull_request.head.sha, annotations_count: context.payload.check_run.annotations_count}, null, 2)}
            \`\`\`

            </details>`;

            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Build coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ | tee pytest-coverage.txt
      
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml